name: Deploy to EC2

on:
  push:
    branches:
      - main  # Ensure this matches your active branch, e.g., 'main' or 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use a GitHub-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          EC2_HOST: "your-ec2-public-ip"
          EC2_USER: "ec2-user"  # Change to "ubuntu" for Ubuntu instances
        run: |
          echo "$EC2_SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            cd /path/to/your/project
            git pull origin main  # Pull changes from the correct branch
            # Restart services if needed, e.g., pm2 restart app
          EOF
